// 
// 匿名
export const ANONYMOUS = "ANONYMOUS";
// 登录超时
export const EVENT_BUS_LOGIN_TIMEOUT = "EVENT_BUS_LOGIN_TIMEOUT";
export const EVENT_BUS_LOGIN_ERROR_400 = "EVENT_BUS_LOGIN_ERROR_400";
export const EVENT_BUS_SERVER_ERROR_500 = "EVENT_BUS_SERVER_ERROR_500";
export const EVENT_BUS_HTTP_ERROR = "EVENT_BUS_HTTP_ERROR";
export const EVENT_BUS_SWITCH_THEME = "EVENT_BUS_SWITCH_THEME";
export const EVENT_BUS_TOKEN_INVALID = "EVENT_BUS_TOKEN_INVALID";
//
export const EVENT_BUS_MESSAGE_TYPE_STATUS = "EVENT_BUS_MESSAGE_TYPE_STATUS";
export const EVENT_BUS_MESSAGE_TYPE_TYPING = "EVENT_BUS_MESSAGE_TYPE_TYPING";
export const EVENT_BUS_MESSAGE_TYPE_PROCESSING =
  "EVENT_BUS_MESSAGE_TYPE_PROCESSING";
export const EVENT_BUS_MESSAGE_TYPE_STREAM_END =
  "EVENT_BUS_MESSAGE_TYPE_STREAM_END";
export const EVENT_BUS_MESSAGE_TYPE_STREAM_ERROR =
  "EVENT_BUS_MESSAGE_TYPE_STREAM_ERROR";
export const EVENT_BUS_MESSAGE_TYPE_PREVIEW = "EVENT_BUS_MESSAGE_TYPE_PREVIEW";
export const EVENT_BUS_MESSAGE_TYPE_CONTENT = "EVENT_BUS_MESSAGE_TYPE_CONTENT";
export const EVENT_BUS_MESSAGE_TYPE_RECALL = "EVENT_BUS_MESSAGE_TYPE_RECALL";
// 
export const ACCESS_TOKEN = "ACCESS_TOKEN";
// 
export const HTTP_CLIENT = "WEB_FLOAT";
// 
export const POST_MESSAGE_CLOSE_CHAT_WINDOW = "CLOSE_CHAT_WINDOW";
export const POST_MESSAGE_MAXIMIZE_WINDOW = "MAXIMIZE_WINDOW";
export const POST_MESSAGE_MINIMIZE_WINDOW = "MINIMIZE_WINDOW";
export const POST_MESSAGE_RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const POST_MESSAGE_INVITE_VISITOR = "INVITE_VISITOR";
export const POST_MESSAGE_INVITE_VISITOR_ACCEPT = "INVITE_VISITOR_ACCEPT";
export const POST_MESSAGE_INVITE_VISITOR_REJECT = "INVITE_VISITOR_REJECT";
// 
export const POST_MESSAGE_LOCALSTORAGE_REQUEST = "LOCALSTORAGE_REQUEST";
export const POST_MESSAGE_LOCALSTORAGE_RESPONSE = "LOCALSTORAGE_RESPONSE";
// 
export const BYTEDESK_UID = "BYTEDESK_UID";
export const BYTEDESK_VISITOR_UID = "BYTEDESK_VISITOR_UID";
// 浏览记录发送失败的时间戳，用于限制1小时内不再发送
export const BYTEDESK_BROWSE_FAILED_TIMESTAMP = "BYTEDESK_BROWSE_FAILED_TIMESTAMP";
// 日志相关常量
export const LOG_ENABLE = "BYTEDESK_LOG_ENABLE";