// 
// 匿名
export const ANONYMOUS = "ANONYMOUS";
// 登录超时
export const EVENT_BUS_LOGIN_TIMEOUT = "EVENT_BUS_LOGIN_TIMEOUT";
export const EVENT_BUS_LOGIN_ERROR_400 = "EVENT_BUS_LOGIN_ERROR_400";
export const EVENT_BUS_SERVER_ERROR_500 = "EVENT_BUS_SERVER_ERROR_500";
export const EVENT_BUS_HTTP_ERROR = "EVENT_BUS_HTTP_ERROR";
export const EVENT_BUS_SWITCH_THEME = "EVENT_BUS_SWITCH_THEME";
export const EVENT_BUS_TOKEN_INVALID = "EVENT_BUS_TOKEN_INVALID";
//
export const EVENT_BUS_MESSAGE_TYPE_STATUS = "EVENT_BUS_MESSAGE_TYPE_STATUS";
export const EVENT_BUS_MESSAGE_TYPE_TYPING = "EVENT_BUS_MESSAGE_TYPE_TYPING";
export const EVENT_BUS_MESSAGE_TYPE_PROCESSING =
  "EVENT_BUS_MESSAGE_TYPE_PROCESSING";
export const EVENT_BUS_MESSAGE_TYPE_STREAM_END =
  "EVENT_BUS_MESSAGE_TYPE_STREAM_END";
export const EVENT_BUS_MESSAGE_TYPE_STREAM_ERROR =
  "EVENT_BUS_MESSAGE_TYPE_STREAM_ERROR";
export const EVENT_BUS_MESSAGE_TYPE_PREVIEW = "EVENT_BUS_MESSAGE_TYPE_PREVIEW";
export const EVENT_BUS_MESSAGE_TYPE_CONTENT = "EVENT_BUS_MESSAGE_TYPE_CONTENT";
export const EVENT_BUS_MESSAGE_TYPE_RECALL = "EVENT_BUS_MESSAGE_TYPE_RECALL";
// 
export const ACCESS_TOKEN = "ACCESS_TOKEN";
// 
export const HTTP_CLIENT = "WEB_FLOAT";
// 
export const POST_MESSAGE_CLOSE_CHAT_WINDOW = "CLOSE_CHAT_WINDOW";
export const POST_MESSAGE_MAXIMIZE_WINDOW = "MAXIMIZE_WINDOW";
export const POST_MESSAGE_MINIMIZE_WINDOW = "MINIMIZE_WINDOW";
export const POST_MESSAGE_RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const POST_MESSAGE_MESSAGE_BUBBLE_CLICK = "MESSAGE_BUBBLE_CLICK";
export const POST_MESSAGE_INVITE_VISITOR = "INVITE_VISITOR";
export const POST_MESSAGE_INVITE_VISITOR_ACCEPT = "INVITE_VISITOR_ACCEPT";
export const POST_MESSAGE_INVITE_VISITOR_REJECT = "INVITE_VISITOR_REJECT";
// 
export const POST_MESSAGE_LOCALSTORAGE_REQUEST = "LOCALSTORAGE_REQUEST";
export const POST_MESSAGE_LOCALSTORAGE_RESPONSE = "LOCALSTORAGE_RESPONSE";
export const POST_MESSAGE_RESET_ANONYMOUS_VISITOR = "RESET_ANONYMOUS_VISITOR";
export const POST_MESSAGE_WINDOW_DRAG_START = "WINDOW_DRAG_START";
export const POST_MESSAGE_WINDOW_DRAG_MOVE = "WINDOW_DRAG_MOVE";
export const POST_MESSAGE_WINDOW_DRAG_END = "WINDOW_DRAG_END";
export const POST_MESSAGE_AUTO_SEND_TEXT = "AUTO_SEND_TEXT";
// 切换显示模式：floating（弹窗） <-> inline（嵌入页面右侧）
export const POST_MESSAGE_TOGGLE_VIEW_MODE = "TOGGLE_VIEW_MODE";
// URL 参数：当前显示模式，供 iframe 内 ChatHeader 渲染对应切换按钮
export const URL_PARAM_VIEW_MODE = "viewMode";
// URL 参数：是否显示“切换显示模式”按钮（默认显示，传 0/false 隐藏）
export const URL_PARAM_TOGGLE_VIEW_MODE_BUTTON = "toggleViewModeButton";
// 
export const BYTEDESK_UID = "BYTEDESK_UID";
export const BYTEDESK_VISITOR_UID = "BYTEDESK_VISITOR_UID";
// 浏览记录发送失败的时间戳，用于限制1小时内不再发送
export const BYTEDESK_BROWSE_FAILED_TIMESTAMP = "BYTEDESK_BROWSE_FAILED_TIMESTAMP";
export const BYTEDESK_BROWSE_LAST_TIMESTAMP = "BYTEDESK_BROWSE_LAST_TIMESTAMP";
// 日志相关常量
export const LOG_ENABLE = "BYTEDESK_LOG_ENABLE";